### ISSUE TITLE
Make wireguard interfaces persistent 

### ISSUE THREAD

**Issue by Lanestolen** [Lanestolen/grpc-router#3]
Start wireguard interfaces after a reboot

**Comment by rasmim** [comment]
What is the status of this issue? I think it still exists? 

BTW, check this error, after the router is restarted. 

![image](https://user-images.githubusercontent.com/28572601/137333806-9022f8c1-e831-4424-b283-d0460460c83f.png)

It happens when I request VPN configuration. 

@Lanestolen

**Comment by rasmim** [comment]
What is the status of this issue?
